### PR TITLE
fix: ensuring we are checking the storage accounts on the whole subscripti…

### LINKED ISSUE #64: Storage account needs to be unique per subscription
**Describe the bug**
Account name needs to be unique per subscription

**To Reproduce**
deploy a quickstart twice and the second time it should complain about account name collision

**Expected behavior**
should use existing storage account the second time around

### PR DESCRIPTION
**Pull request by softchris**
…on instead of by resource group

# Pull Request Template

## Description

storage accounts are unique by subscription NOT by resource group. So when we check for a storage account we need to check the whole subscription otherwise we risk a name collision

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How to Test

- try deploying a quickstart twice and you will get an error complaining about account name taken already

## Closing issues

closes #64 

## Assignee

Please add yourself as the assignee

## Projects

Please add relevant projects so this issue can be properly tracked.

### CODE REVIEW

File: src/util/azure/account.ts [hunk 1]
```diff
@@ -82,14 +83,16 @@ export async function getAccount(
...
-      accountName = await generateDefaultAccountName(initialName);
-      needToCreateAccount = true;
-    } else {
-      // select from list or create new
-      const result = await filteredList(accounts as AccountDetails[], accountPromptOptions, newAccountPromptOptions);
-      needToCreateAccount = !!result.newAccount;
-      accountName = result.newAccount || result.account.name;
-    }
+  
+      accountName = yield generateDefaultAccountName(initialName);
```
Comment (manekinekko) [inline src/util/azure/account.ts]:
```suggestion
      accountName = await generateDefaultAccountName(initialName);
```

File: src/util/azure/account.ts [hunk 2]
```diff
@@ -82,14 +83,16 @@ export async function getAccount(
...
+      const availableResult = yield client.storageAccounts.checkNameAvailability(accountName);
```
Comment (manekinekko) [inline src/util/azure/account.ts]:
```suggestion
      const availableResult = await client.storageAccounts.checkNameAvailability(accountName);
```

File: src/util/azure/account.ts [hunk 3]
```diff
@@ -82,13 +73,16 @@ export async function getAccount(
...
-    } else {
-      // select from list or create new
-      const result = await filteredList(accounts as AccountDetails[], accountPromptOptions, newAccountPromptOptions);
-      needToCreateAccount = !!result.newAccount;
-      accountName = result.newAccount || result.account.name;
+      const availableResult = await client.storageAccounts.checkNameAvailability(accountName);
+
+      if (!availableResult.nameAvailable) {
+        logger.info(`Account ${accountName} already exist on subscription`);
+        logger.info(`Using existing account ${accountName}`);
```
Comment (manekinekko) [inline src/util/azure/account.ts]: We can maybe merge the two message into one.
